# Generated by Django 4.0.4 on 2022-06-23 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='add_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=50, verbose_name='User name'),
        ),
    ]
