# Generated by Django 4.0.4 on 2022-06-23 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_meme_add_by_alter_user_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='likes',
            field=models.ManyToManyField(related_name='liked', to='website.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='credentials',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='meme',
            name='add_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='author', to='website.user'),
        ),
    ]
