# Generated by Django 4.0.4 on 2022-06-25 13:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0003_meme_likes_user_credentials_alter_meme_add_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='User2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='User name')),
                ('email', models.EmailField(max_length=254, verbose_name='User email')),
                ('credentials', models.IntegerField(default=2)),
            ],
        ),
        migrations.AlterField(
            model_name='meme',
            name='add_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meme',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Add date'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='likes',
            field=models.ManyToManyField(related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meme',
            name='pantone',
            field=models.CharField(default='Pantone 0', max_length=20, verbose_name='Pantone'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
