# Generated by Django 4.0.4 on 2022-06-26 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_meme_add_by_alter_meme_add_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 26, 14, 15, 53, 1867), verbose_name='Add date'),
        ),
    ]
